version: "3"

services:
  broker-mqtt-reports:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - broker-mqtt-data-reports:/mosquitto/data            
  store-mongo-reports:
    image: mongo:4
    ports:
      - "27017:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - store-mongo-db-reports:/data/db
  keycloak-mysql-reports:
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
         - MYSQL_ROOT_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
     volumes:
       - keycloak-mysql-data-reports:/var/lib/mysql
  keycloak-reports:
       image: nebulaepyxis/keycloak:latest
       environment:
         - MYSQL_ADDR=keycloak-mysql-reports
         - MYSQL_PORT_3306_TCP_ADDR=keycloak-mysql-reports
         - MYSQL_PORT_3306_TCP_PORT=3306
         - KEYCLOAK_USER=keycloak
         - KEYCLOAK_PASSWORD=keycloak
         - MYSQL_DATABASE=keycloak
         - MYSQL_USER=keycloak
         - MYSQL_PASSWORD=keycloak
         - SERVICE_PORTS=8080
       ports:
         - 8443:8443
         - 8080:8080
         - 9990:9990
       volumes:
         - keycloak-data-reports:/opt/jboss/keycloak/standalone/data      
       depends_on: 
         - keycloak-mysql-reports
volumes: 
  store-mongo-db-reports:
  broker-mqtt-data-reports:
  keycloak-mysql-data-reports:
  keycloak-data-reports: