



type BusinessReportDashboardBonusLineChartTimeDataset{
  timespan: String,
  scale: String,
  order: Int,
  labels: [String],
  datasets: [BusinessReportDashboardBonusLineChartSubtimeDataset]
}

type BusinessReportDashboardBonusLineChartSubtimeDataset{
  order: Int,
  label: String,
  data: [Float]
}

type BusinessReportDashboardNetBonusDistributionTimeDataSet{
    timespan: String,    
    datasets: [BusinessReportDashboardNetBonusDistributionSubtime]
}

type BusinessReportDashboardNetBonusDistributionSubtime{
  timespan: String,    
  dataset: [BusinessReportDashboardNetBonusDistributionSubtimeDataset]
}

type BusinessReportDashboardNetBonusDistributionSubtimeDataset{
   product: String, 
   percentage: Float, 
   value: BigInt, 
   count: Int
}


type BusinessReportDashboardNetSalesDistributionTimeDataSet{
    timespan: String,    
    datasets: [BusinessReportDashboardNetSalesDistributionSubtime]
}

type BusinessReportDashboardNetSalesDistributionSubtime{
  timespan: String,    
  dataset: [BusinessReportDashboardNetSalesDistributionSubtimeDataset]
}

type BusinessReportDashboardNetSalesDistributionSubtimeDataset{
   product: String, 
   percentage: Float, 
   value: BigInt, 
   count: Int
}

type BusinessReportDashboardSalesOverviewTimeDataSet{
    timespan: String,  
    datasets: [BusinessReportDashboardNetSalesDistributionSubtime]  
}

type BusinessReportDashboardNetSalesDistributionSubtime{
  timespan: String,  
  scale: String,
  labels: [String],
  datasets: BusinessReportDashboardNetSalesDistributionSubtimeDatasets
}

type BusinessReportDashboardNetSalesDistributionSubtimeDatasets{
  mainSales: [BigInt],
  bonusSales: [BigInt],
  creditSales: [BigInt],
  mainBalance: [BigInt],
  bonusBalance: [BigInt],
  salesQty: [BigInt],
  bonusQty: [BigInt],
}

type BusinessReportDashboardWalletStatusCards{
  spendingAllowed: Boolean,
  pockets: [BusinessReportDashboardWalletStatusCardsPocket]
}

type BusinessReportDashboardWalletStatusCardsPocket{
  order: Int,
  name: String,
  balance: BigInt,
  lastUpdate:BigInt,
  currency: String,
}


type Query{
  businessReportDashboardBonusLineChart(businessId: String): [BusinessReportDashboardBonusLineChartTimeDataset]
  businessReportDashboardNetBonusDistribution(businessId: String): [BusinessReportDashboardNetBonusDistributionTimeDataSet]
  businessReportDashboardNetSalesDistribution(businessId: String): [BusinessReportDashboardNetSalesDistributionTimeDataSet]
  businessReportDashboardSalesOverview(businessId: String): [BusinessReportDashboardSalesOverviewTimeDataSet]
  businessReportDashboardWalletStatusCards(businessId: String): BusinessReportDashboardWalletStatusCards

}

